Initialize state with mt19937 random numbers
NOAA-GSL/SENA-crtm pull request #1
Opened 2021-10-22 21:45 UTC by christopherwharrop-noaa

Add mt19937 routines for computing random numbers so that initialization is reproducible across compilers/platforms.

Add routines for printing state variable statistics for verification.

2021-10-22 22:32 UTC, dshawul approved these changes

2021-10-22 23:18 UTC, dshawul requested changes
--

2021-10-22 23:20 UTC, danielabdi-noaa approved these changes
This is a pretty nice way of dealing with inconsistency in random number generation across compilers. I have tested the CPU version and like the way all variable state is printed before and after computation. This should enable ctest easily.

2021-10-22 23:21 UTC, merged

2021-10-25 16:09 UTC, robgpita commented
Looks good! Looking forward to having the input data included in this repo to run the test suite.

2021-10-25 16:13 UTC, robgpita commented on ref/src/kernel.F90
> +    WRITE(*,'(A5, A17,5ES20.10)') "TEST ", name, minval(data), maxval(data), data(1,1), &
Glad the lessons learned from c_sw to print scientific notation in compliance with C standards made it in here.